### ISSUE TITLE
Cursor support

### ISSUE THREAD

**Issue by suan** [TheZero0-ctrl/erb-commenter#2]
Not sure the exact issue,  but it doesn’t work with the Cursor AI IDE, which is a fork of vscode, even after I downloaded and loaded the extension manually.

Would be nice to get cursor support

**Comment by TheZero0-ctrl** [comment]
To use this extension, you first need to install Ruby or a Ruby LSP-related extension. This is a requirement for now, but I might make it work independently in the future.

**Comment by suan** [comment]
That was it, thanks! Would be good to mention a Ruby extension being a prerequisite, but I will close this issue for now
