### ISSUE TITLE
request logo in vscode and marketplace

### ISSUE THREAD

**Issue by maprangsoft** [TheZero0-ctrl/erb-commenter#3]
this extension the best i want have logo on vscode and marketplace 

![Screen Shot 2567-10-20 at 17 38 38](https://github.com/user-attachments/assets/df35b89a-61b6-4886-8366-6634b6b91dd7)

![Screen Shot 2567-10-20 at 17 38 05](https://github.com/user-attachments/assets/582fb781-667c-47a0-93b6-020cd72c4496)

thank you advance.

**Comment by TheZero0-ctrl** [comment]
I'm glad you like it, but I don't think a logo is necessary.

**Comment by maprangsoft** [comment]
ok i understand. 😊
